### ISSUE TITLE
[기능] 채팅방 구분 기능

### ISSUE THREAD

**Issue by JMKiim** [Hanghae99-Clone-99Code/99Code-FE#10]
## To-Do
- [x] 채팅방 CR (Update, Delete 제외)
- [x] 채팅방 초대기능 구현
- [x] 채팅방 제목 클릭 시 드롭다운
- [x] 특정 채팅방 유저 목록
