### ISSUE TITLE
[조사] 웹소켓과 소켓 통신 관련 자료 조사

### ISSUE THREAD

**Issue by JMKiim** [Hanghae99-Clone-99Code/99Code-FE#2]
## 설명
디스코드 클론 코딩에서 핵심 기능인 실시간 채팅 기능 구현을 위한 자료 조사

## To-Do
- [x] 웹소켓
- [x] 클라이언트 - 서버 간 소켓 통신 흐름
- [x] SockJS-Client, StompJS 라이브러리
- [x] 실시간으로 주어지는 정보를 React에서 처리할 방법
