### ISSUE TITLE
[기능] 실시간 채팅

### ISSUE THREAD

**Issue by JMKiim** [Hanghae99-Clone-99Code/99Code-FE#3]
## To-Do
- [x] local 환경에서 간이 Node.js 서버와 연결 후 Socket emit, on 테스트
- [x] 채팅 방, 사용자 정보, 보낸 메시지 관리
- [x] API와 연결 후 저장된 채팅 기록 CR (Delete, Update 제외)

## ETC
불필요한 채팅 기록 GET 요청이 많을 수 있을 것으로 예상 됨, 해결 방안 모색
